language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

after_success:
  - codecov
  - mvn package -pl ugs-core assembly:assembly
  - mvn install
  - mvn install -pl ugs-platform/application -Pcreate-dmg

before_script:
  - pip install --user codecov
  - sudo apt-get update -qq
  - sudo apt-get install -qq genisoimage

deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: ugs-platform/application/target/ugs-platform-app-2.0-SNAPSHOT.dmg
    user: breiler
    key: $BINTRAY_API_KEY